services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    environment:
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpass
      CLICKHOUSE_DB: default
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse/init:/docker-entrypoint-initdb.d:ro
      - ./clickhouse/config.d:/etc/clickhouse-server/config.d:ro
      - ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1' >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio12345
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mc-init:
    image: quay.io/minio/mc:latest
    container_name: mc-init
    depends_on:
      - minio
    entrypoint: >
      sh -c "
      until /usr/bin/mc alias set local http://minio:9000 minio minio12345; do sleep 2; done &&
      /usr/bin/mc mb -p local/ingestion || true &&
      echo 'bucket ingestion pronto'
      "

  ingestor:
    image: python:3.12-slim
    container_name: ingestor
    depends_on:
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_started
    working_dir: /app
    volumes:
      - ./ingestion:/app:ro
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio12345
      S3_BUCKET: ingestion
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpass
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_TABLE: data_ingestion
      BATCH_SIZE: "50000"
    command: >
      sh -c "pip install --no-cache-dir minio clickhouse-connect pandas requests &&
             python script.py"

  transformer:
    image: python:3.12-slim
    container_name: transformer
    depends_on:
      clickhouse:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./transform:/app/transform:ro
    environment:
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: chpass
      CLICKHOUSE_DATABASE: default
      SRC_TABLE: default.data_ingestion
      DST_TABLE: default.working_g2
      BATCH_SIZE: "5000"
    command: >
      sh -c "pip install --no-cache-dir clickhouse-connect pydantic &&
             python -m transform.transform"

volumes:
  ch_data:
  minio_data:
